graph_slam:
  ros__parameters:
    finish_line_offset: 0.0
    track_width: 3.0
    min_lap_distance: 30.0
    max_pose_edges: 2500
    max_landmark_edges: 5000
    verbose: true
    pos_lidar_x: 1.5
    perception_topic: "/perception/map"
