graph_slam:
  ros__parameters:
    finish_line_offset: 0.0
    track_width: 3.0
    min_lap_distance: 30.0
    write_csv: false
    max_pose_edges: 10000
    max_landmark_edges: 10000
    verbose: false
    perception_topic: "/perception/map"
