path_planning:
  ros__parameters:
    perception_topic: '/slam/map'
    triangulation_topic: '/path_planning/triangulation'
    trajectory_topic: '/path_planning/trajectory'
    
    # Triangulation parameters
    max_tri_len: 7.5
    max_tri_angle: 2.9
    color: true

    # Route parameters
    len_coeff: 0.25
    angle_coeff: 0.75
    max_angle: 1.0
    prev_route_bias: 0.5

    # Profile creation parameters
    v_max: 5.0
    ay_max: 3.0
    ax_max: 3.0

    # Trajectory generation parameters
    smooth: 0.3     # in (0, 0.5) interval