path_planning:
  ros__parameters:
    perception_topic: '/slam/map'
    triangulation_topic: '/path_planning/triangulation'
    trajectory_topic: '/path_planning/trajectory'
    max_tri_len: 7.5
    max_tri_angle: 2.9
    len_coeff: 0.25
    angle_coeff: 0.75
    max_angle: 1.0
    v_max: 10.0
    ay_max: 5.0
    ax_max: 5.0