path_planning:
  ros__parameters:
    map_topic: '/slam/map'
    triangulation_topic: '/path_planning/triangulation'
    trajectory_topic: '/path_planning/trajectory'
    points_to_optimize_topic: '/path_planning/midpoints_to_optimize'

    # Triangulation parameters
    max_tri_len: 7.5
    max_tri_angle: 3.15
    color: true

    # Route parameters
    len_coeff: 0.02
    angle_coeff: 0.98
    max_angle: 1.15
    route_back: 10
    prev_route_bias: 0.5
    use_buffer: false

    # Profile creation parameters
    v_max: 2.0
    ay_max: 3.0
    ax_max: 3.0