path_planning:
  ros__parameters:
    perception_topic: '/arussim/perception'
    triangulation_topic: '/path_planning/triangulation'
    trajectory_topic: '/path_planning/trajectory'
    dist_coeff: 0.5
    angle_coeff: 0.75
    max_dist: 4.0
    max_angle: 1.5
    max_route: 20