visualization:
  ros__parameters:
    alpha: 0.7

    # Topics to subscribe
    triangulation_topic: '/path_planning/triangulation'
    optimized_trajectory_topic: '/trajectory_optimization/trajectory'
    arussim_trajectory_topic: '/arussim_interface/fixed_trajectory'
    # Topics to publish
    triangulation_visualization_topic: '/visualization/triangulation'
    optimized_trajectory_visualization_topic: '/visualization/trajectory_optimized'
    arussim_trajectory_visualization_topic: '/visualization/arussim_fixed_trajectory'