car_state:
  ros__parameters:
    get_arussim_ground_truth: false
    simulation: false
    mission: "autocross"

    safe_mode: false

    # Following parameters only used in safe mode for plausability checks
    dt_threshold_imu: 0.05
    dt_threshold_extensometer: 0.05
    dt_threshold_wheelspeed: 0.05
    dt_threshold_inv: 0.05
    dt_threshold_cones_count_actual: 0.25
    dt_threshold_cones_count_all: 0.25

    max_ax: 15.0
    max_ay: 15.0
    max_r: 15.0
    max_vx: 75.0
    max_plausability_error: 20.0

    error_weight_imu: 2.0
    error_weight_extensometer: 2.0
    error_weight_wheel_speed: 2.0
    error_weight_inv_speed: 2.0
    error_weight_cones_count_actual: 11.0
    error_weight_cones_count_all: 11.0