controller:
  ros__parameters:
    # Wheter to restart the map at the origin after a loop closure
    restart_at_origin: true
    # Iterations after which to restart the map. -1 to disable
    restart_iterations: -1