controller:
  ros__parameters:
    controller_type: "pure_pursuit"    # change between (can be "mpc", "pure_pursuit", "stanley", "pid", etc.)
    timer_frequency: 5.0          # timer frecuency in Hz

    #PID
    TARGET_SPEED: 2
    KP: 0.0
    KD: 0.0
    KI: 0.0
