controller:
  ros__parameters:
    # Topics
    state_topic: "/car_state/state"
    run_check_topic: "/car_state/run_check"
    trajectory_topic: "/path_planning/trajectory"
    optimized_trajectory_topic: "/trajectory_optimization/trajectory"
    cmd_topic: "/controller/cmd"
    pursuit_point_topic: "/controller/pursuit_point"
    target_speed_topic: "/controller/target_speed"
    braking_procedure_topic: "/car_state/braking_procedure"

    # Parameters
    use_optimized_trajectory: False   # use optimized trajectory
    first_lap_steer_control: "PP"     # PP, MPC
    optimized_steer_control: "PP"     # PP, MPC
    speed_timer_frequency: 100.0      # speed timer frecuency in Hz
    steer_timer_frequency: 50.0       # steer timer frecuency in Hz

    # PP
    look_ahead_distance: 4.0
    optimized_look_ahead_distance: 7.0

    # MPC
    cost_lateral_error: 5.0
    cost_angular_error: 10.0
    cost_steering_delta: 3000.0
    compensation_steps: 6

    # PID
    target: 5.0
    braking_decc: 3.0
    KP: 10.0
    KI: 0.55
    KD: 0.01

    # Cmd
    min_cmd: 0.0    # % inv
    max_cmd: 0.1    # % inv
    max_steer: 20.0 # degrees

    # Vehicle parameters
    rho: 1.225      # air density
    CdA: 1.2        # drag coefficient
    Crr: 0.01       # rolling resistance coefficient
    mass: 230       # mass of the vehicle
    g: 9.81         # gravity

    debug: true