controller:
  ros__parameters:
    controller_type: "pure_pursuit"    
    timer_frequency: 100.0          # timer frecuency in Hz

    # Topics
    state: "/car_state/state"
    as_status: "/can/AS_status"
    as_check: "/car_state/AS_check"
    trajectory: "/path_planning/trajectory"
    cmd: "/controller/cmd"
    pursuit_point: "/controller/pursuit_point"

    # PP
    look_ahead_distance: 6.0

    # PID
    target: 5.0
    KP: 43.87
    KI: 0.0
    KD: 0.0

    # Cmd
    min_cmd: 0.0
    max_cmd: 0.1
