controller:
  ros__parameters:
    first_lap_steer_control: "PP"   # PP, MPC
    optimized_steer_control: "PP"   # PP, MPC
    timer_frequency: 100.0          # timer frecuency in Hz

    # Topics
    state: "/car_state/state"
    as_status: "/can/AS_status"
    as_check: "/car_state/AS_check"
    trajectory: "/path_planning/trajectory"
    cmd: "/controller/cmd"
    pursuit_point: "/controller/pursuit_point"
    target_speed: "/controller/target_speed"

    # PP
    look_ahead_distance: 6.0

    # PID
    target: 5.0
    KP: 10.0
    KI: 0.55
    KD: 0.01

    # Cmd
    min_cmd: 0.0    # % inv
    max_cmd: 0.1    # % inv
    max_steer: 20.0 # degrees
