perception:
  ros__parameters:
    # Parameters of topic
    lidar_topic: "/rslidar_points"
    state_topic: "/car_state/state"

    # Parameters of cropping
    crop: true
    max_x_fov: 50.0
    max_y_fov: 25.0
    max_z_fov: 1.5

    # Parameters of ground filter
    threshold_ground_filter: 0.05
    number_sections: 100
    angle_threshold: 35.0

    # Parameters of clustering and filtering
    min_cluster_size: 4
    max_cluster_size: 200
    radius: 0.15

    #Parameters of scoring
    threshold_scoring: 0.0

    #Parameters of coloring
    kColor: false
    distance_threshold: 5.0
    coloring_threshold: 15.0

    # Parameters of debugging
    debug: true