perception:
  ros__parameters:
    #Topic
    lidar_topic: "/rslidar_points"
    state_topic: "/car_state/state"

    #Parameters of FOV
    crop: true
    max_x_fov: 30.0
    max_y_fov: 15.0
    max_z_fov: 0.0

    #Parameters of ground filter
    threshold_ground_filter: 0.075

    number_sections: 8
    angle_threshold: 35.0
    minimum_ransac_points: 30

    # Parameters of accumulation
    accumulation_clouds: false
    accumulation_clusters: false
    buffer_size: 5
    accumulation_threshold: 0.01

    #Parameters of clustering
    radius: 0.15

    #Parameters of scoring
    min_threshold_scoring: 0.90
    max_threshold_scoring: 0.95

    #Parameters of coloring
    distance_threshold: 5.0
    coloring_threshold: 15.0