perception:
  ros__parameters:
    #Topic
    lidar_topic: "/rslidar_points"

    #Parameters of FOV
    max_x_fov: 25.0
    max_y_fov: 20.0
    max_z_fov: 0.0
    h_fov: 180.0

    #Parameters of ground filter
    threshold_ground_filter: 0.05

    #Parameters of clustering
    radius: 0.15

    #Parameters of scoring
    threshold_scoring: 0.85