perception:
  ros__parameters:
    # Topics
    lidar_topic: "/rslidar_points"
    state_topic: "/car_state/state"
    perception_topic: "/perception/map"

    accum_cloud_topic: "/perception/accumulated_cloud"
    filtered_cloud_topic: "/perception/filtered_cloud"
    clusters_cloud_topic: "/perception/clusters_cloud"

    lidar_cog_x_offset: 1.5


    # Accumulation parameters
    accum_buffer_size: 10
    voxel_filter: false
    voxel_size_x: 0.1
    voxel_size_y: 0.1
    voxel_size_z: 0.1

    # Cropping parameters
    crop: false
    max_x_fov: 50.0
    max_y_fov: 25.0
    max_z_fov: 10.0

    # Ground filter parameters
    ground_filter_type: "Z_FILTER"        # Options: "RANSAC", " RANSAC_GRID", "PILLAR", "Z_FILTER"
    threshold_ground_filter: 0.05
    number_sections: 30
    angle_threshold: 35.0

    # Clustering parameters
    min_cluster_size: 4
    max_cluster_size: 200
    tolerance: 0.5

    # Reconstruction parameters
    reconstruction: false
    reconstruction_radius: 0.15

    # Scoring parameters
    threshold_scoring: 0.0

    # Coloring parameters
    kColor: false
    distance_threshold: 25.0
    coloring_threshold: 15.0

    # Parameters of debugging
    debug: true