skidpad_planning:
  ros__parameters:
    perception_topic: "/slam/map"
    trajectory_topic: "/skidpad_planning/trajectory"
    planning_time: 5.0      # seconds comuting the skidpad centers
    target_first_lap: 5.0
    target_second_lap: 10.0
    route_spacing: 0.5
    top_accx_forwards: 5.0
    top_accx_backwards: 7.0
    top_accy: 6.0
    step_width_1 : 0.0
    step_width_2 : 0.0
