perception_acc:
  ros__parameters:
    #Topic
    lidar_topic: "/rslidar_points"

    #Accumulation
    voxel_size: 0.3
    clouds_matched: 1
    buffer_size: 5

    #Parameters of FOV
    crop: true
    max_x_fov: 40.0
    max_y_fov: 40.0
    max_z_fov: 0.5

    #Parameters of ground filter
    threshold_ground_filter: 0.2

    number_sections: 8
    angle_threshold: 35.0
    minimum_ransac_points: 30

    #Parameters of clustering
    radius: 0.15

    #Parameters of scoring
    threshold_scoring: 0.60

    #Parameters of coloring
    distance_threshold: 5.0
    coloring_threshold: 15.0