perception_acc:
  ros__parameters:
    #Topic
    lidar_topic: "/fast_limo/pointcloud"

    #Accumulation
    distance_lidar_to_CoG: 1.75
    buffer_size: 7

    #Parameters of FOV
    crop: true
    max_x_fov: 25.0
    max_y_fov: 25.0
    max_z_fov: 0.5

    #Parameters of ground filter
    threshold_ground_filter: 0.1

    number_sections: 8
    angle_threshold: 5.0
    minimum_ransac_points: 30

    #Parameters of clustering
    radius: 0.15

    #Parameters of scoring
    threshold_scoring: 0.75

    #Parameters of coloring
    distance_threshold: 5.0
    coloring_threshold: 15.0