trajectory_optimization:
  ros__parameters:
    v_max: 15.0
    d_min: 1.3
    mu_y: 0.9
    mu_throttle: 0.5
    mu_brake: 0.5
    n_iter: 3
    n_seg: 1000

    #Topic
    optimized_trajectory_topic: "/trajectory_optimization/trajectory"
    track_limits_topic: "/path_planning/track_limits"
    
