trajectory_optimization:
  ros__parameters:
    #Trajectory optimization
    n_iter: 3
    n_seg: 1000
    d_min: 1.3

    #Profile generation
    v_max: 15.0
    mu_y: 0.9
    mu_throttle: 0.5
    mu_brake: 0.5

    #Car parameters
    g: 9.81
    m: 270.0
    c_L: 2.1
    c_D: 0.72
    
    #Topics
    optimized_trajectory_topic: "/trajectory_optimization/trajectory"
    track_limits_topic: "/path_planning/track_limits"

    #Debug
    debug: true
    
