trajectory_optimization:
  ros__parameters:
    ax_max: 3.
    ay_max: 1.5
    v_max: 8.
    d_max: 0.7

    #Topic
    trajectory: "/arussim_interface/fixed_trajectory"
    car_state: "/car_state/state"
    optimized_trajectory: "/trajectory_optimizer/trajectory"

    