trajectory_optimization:
  ros__parameters:
    ax_max: 3.
    ay_max: 9.
    v_max: 20.
    d_min: 1.2

    #Topic
    trajectory_topic: "/path_planning/midpoints_to_optimize"
    car_state_topic: "/car_state/state"
    optimized_trajectory_topic: "/trajectory_optimization/trajectory"
    track_limits_topic: "/path_planning/track_limits"
    