trajectory_optimization:
  ros__parameters:
    v_max: 20.
    d_min: 1.3
    mu_y: 1.1
    mu_throttle: 0.6
    mu_brake: 0.9

    #Topic
    trajectory_topic: "/path_planning/midpoints_to_optimize"
    car_state_topic: "/car_state/state"
    optimized_trajectory_topic: "/trajectory_optimization/trajectory"
    track_limits_topic: "/path_planning/track_limits"
    