name: Test DRIVERLESS2

permissions:
  contents: read
  packages: read

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/arusfs/arus:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: /workspace

    steps:
    - name: Checkout DRIVERLESS2
      uses: actions/checkout@v4

    - name: Clone DRIVERLESS_TESTS
      run: |
        mkdir -p /workspace/src
        cd /workspace/src
        git clone https://github.com/ARUSfs/DRIVERLESS_TESTS.git

    - name: Build workspace
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        cd /workspace
        colcon build --packages-ignore arussim_interface

    - name: Run tests
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        source /workspace/install/setup.bash
        cd /workspace
        colcon test
        colcon test-result --all
