name: Test DRIVERLESS2

permissions:
  contents: read
  packages: read

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/arusfs/arus:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: /_w

    steps:
    - name: Checkout DRIVERLESS2
      uses: actions/checkout@v4
      with:
        path: /_w

    - name: Clone DRIVERLESS_TESTS
      run: |
        mkdir -p /_w
        cd /_w
        git clone https://github.com/ARUSfs/DRIVERLESS_TESTS.git  # Clone directly to _w

    - name: Build workspace
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        cd /_w
        colcon build --packages-ignore arussim_interface

    - name: Run tests
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        source /_w/install/setup.bash  # Use _w for setup
        cd /_w
        colcon test
        colcon test-result --all
